apiVersion: apps/v1
kind: Deployment
metadata:
  name: movie-frontend-deployment
  labels:
    app: movie-frontend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: movie-frontend
  template:
    metadata:
      labels:
        app: movie-frontend
    spec:
      containers:
        - name: movie-frontend
          image: 57sprak/movie-frontend:latest
          ports:
            - containerPort: 3000
          env:
            - name: NODE_ENV
              value: "development"
